# Difference b/w Array, List and Tensors

## 🔹 What is an Array?
An **array** is a data structure that stores a **collection of elements of the same type** in a **continuous block of memory**.

👉 Think of it like an **egg tray** 🥚:
- All slots (indexes) are the same size.  
- Each slot holds one element.  
- You can quickly find any egg (element) by its position (index).  

---

## 🔹 Characteristics of Arrays
1. **Same Data Type** → All elements must be of the same type.  
   Example: `[1, 2, 3, 4]` ✅ but `[1, "apple", 3.5]` ❌ (not a true array).  

2. **Fixed Size** (in most languages) → Number of elements is set at creation.  

3. **Index-Based Access** → Each element has an index (starting from 0).  

4. **Stored in Contiguous Memory** → Makes arrays very fast for access.  

---

## 🔹 Types of Arrays
- **0D array** → Single value (scalar).  
- **1D array** → Line of elements.  
- **2D array** → Table (rows & columns).  
- **3D array** → Cube-like structure.  
- **ND array** → Higher dimensions.  

---

## 🔹 Arrays in Python
Python has multiple ways to handle arrays:
- **Lists** (flexible, can hold mixed types, but not true arrays).  
- **array module** (basic arrays).  
- **NumPy arrays** (most powerful, used in Data Science & ML).  

---


## Why NumPy Arrays Are Faster Than Python Lists?

- Contiguous Memory Allocation
- Homogeneous Data Type
- Vectorization (No Loops in Python) 
- Broadcasting (operations without explicit loops)

In [1]:

import numpy as np

arr = np.array([10, 20, 30, 40])
print("Array:", arr)
print("First element:", arr[0])
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)

Array: [10 20 30 40]
First element: 10
Shape: (4,)
Dimensions: 1


### LET's COMPARE THE PROCESSIG SPEED OF LIST AND ARRAY

In [2]:
import numpy as np
import time

# Python list
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]
start = time.time()
result = [x + y for x, y in zip(list1, list2)]
print("List time:", time.time() - start)

# NumPy array
arr1 = np.arange(1000000)
arr2 = np.arange(1000000)
start = time.time()
result = arr1 + arr2
print("NumPy time:", time.time() - start)


List time: 0.05467343330383301
NumPy time: 0.009345293045043945


# Why Lists Store Elements as Objects (and Use More Memory)

In Python, **lists** are very flexible but less memory-efficient compared to **NumPy arrays**.  
This happens because **lists store elements as objects**.

---

## 1. Everything in a Python List is an Object
- In a Python list, each element is actually a **reference (pointer)** to a Python object stored elsewhere in memory.
- Example: If you write `my_list = [1, 2, 3]`, the list stores **pointers** to three separate integer objects (`1`, `2`, `3`).

---

## 2. Extra Memory Usage
- Each object in Python (like an integer) carries:
  - Type information (so Python knows it's an `int`, `float`, `str`, etc.).
  - Reference count (used by garbage collection).
  - The actual value.

- Because of this **metadata overhead**, lists use more memory compared to arrays.

---

## 3. Flexibility Comes at a Cost
- Lists can store **mixed data types**: `[1, "hello", 3.14, True]`.
- This flexibility means Python must store everything as an **object reference**, not as raw numbers in memory.
- Result → **Slower performance** and **more memory usage**.

---

## 4. Why NumPy is Different
- NumPy arrays store elements in **contiguous blocks of memory** with a **fixed data type** (e.g., all `float32` or all `int64`).
- This removes object overhead → much faster and memory-efficient.

---

## 👉 Memory Trick 🧠:

List = A shelf with books + sticky notes pointing to them 📚📌 (extra memory).

NumPy array = A clean row of books without notes 📚 (compact).


In [ ]:
# 🔹 Example: Memory usage of list vs NumPy array

import sys
import numpy as np

py_list = list(range(10))
np_array = np.arange(10)

print("Memory used by Python list:", sum(sys.getsizeof(x) for x in py_list) + sys.getsizeof(py_list), "bytes")
print("Memory used by NumPy array:", np_array.nbytes, "bytes")


Memory used by Python list: 416 bytes
Memory used by NumPy array: 80 bytes


## different ways of creating array in different context


In [ ]:
# 1 Using Python List (Most Common)

arr = [i for i in range(6)]
print(arr)

# With repeated values
arr = [0] * 5   # [0, 0, 0, 0, 0]

# Using range
arr = list(range(5))   # [0, 1, 2, 3, 4]




# 2 Using array Module

'''| Code  | Meaning                    
| ----- | --------------------------- |
| `'i'` | Integer                     |
| `'f'` | Float                       |
| `'d'` | Double (more precise float) |
| `'b'` | Signed char (small int)     |
| `'u'` | Unicode character           |
'''

import array 

arr = array.array('i', [1,2,3,4])



[0, 1, 2, 3, 4, 5]


array([[1, 2, 3],
       [4, 5, 6]])

## Array in NUMPY

- we can also create array by using numpy library
- Numpy array's are hetrogenous

### What is Vectorized Operation?
- Vectorization = performing operations on entire arrays at once (no explicit loops)

- Vectorization works by executing operations on entire arrays using optimized C-level loops and contiguous memory, avoiding Python-level iteration




- Vectorization works best when:

    - Operations are element-wise
    - Data fits in memory

- Sometimes:
  - 👉 loops are still needed (complex logic)


- Funcs

    - NumPy uses Universal Functions (ufuncs):

 - Examples:

- np.add
- np.multiply
- np.exp

## Opration on Array

In [5]:
#1 reversing array

import array 

arr = array.array('i', [1,2,3,4,5])

arr.reverse()



In [ ]:
# vectorized operation 

import numpy as np

arr = np.array([1, 2, 3])

print(arr + 5)



'''

[1, 2, 3]
[5, 5, 5]   ← (virtually expanded)
-----------
[6, 7, 8]

'''


[6 7 8]


In [ ]:
#multi dimential array 

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr

array([[1, 2, 3],
       [4, 5, 6]])

## What is Broadcasting?

- Broadcasting = NumPy automatically “stretches” smaller arrays to match larger ones so element-wise operations can happen.

- No data is physically copied (in most cases). It’s a view-like expansion used during computation.




In [ ]:
# simplest case

a = np.array([[1,2,3],
          [4,5,6]])

b = np.array([2,4,6])

print(a + b)




[[ 3  6  9]
 [ 6  9 12]]


'\n[1, 2, 3]\n[5, 5, 5]   ← (virtually expanded)\n-----------\n[6, 7, 8]\n\n'

In [ ]:
#2 insertion 

print("arr original elements \n", arr)
# lets insert 20 in arr at position 1. by doing so all the existing elements shifts one index forword.

arr.insert(1, 10)
print("after insertion at index 1 \n",arr)

# lets insert any digit in end of array

arr.append(20)
print("after appending \n",arr)

# lets replace any index value with anther

arr[1] = 6
print("after replacing \n",arr)


#copy elements of one array to new array
new_array = array.array(arr.typecode, (x for x in arr))

print("coping elements of arr to new array")

for i in range(0, len(new_array)):
    print(new_array[i], end = " ")

arr original elements 
 array('i', [5, 4, 3, 2, 1])
after insertion at index 1 
 array('i', [5, 10, 4, 3, 2, 1])
after appending 
 array('i', [5, 10, 4, 3, 2, 1, 20])
after replacing 
 array('i', [5, 6, 4, 3, 2, 1, 20])
coping elements of arr to new array
5 6 4 3 2 1 20 

In [8]:
#take n number from user and create an array and add them

import array

arr = array.array('i', [])

n = int(input('how many numbers you want to add'))

for i in range(n):
    num = int(input(f"Enter Number: {i+1}:"))
    arr.append(num)


print(arr)


array('i', [1, 2])


# list 
-  a list is a built-in data structure that is used to store multiple items in a single variable. 
- Lists are dynamic → can grow or shrink in size.
- Lists are ordered, mutable (changeable), and allow duplicate values. 
- Ordered means the elements in a list keep their position (index). Python remembers the order in which you insert items.
- Mutable means you can modify the list after creating it.
- Heterogeneous – They can store different data types (integers, strings, floats, objects, etc.).
- Think of a list as a shopping cart 🛒 → you can add, remove, or mix items of different types.

❗ Compare with “Unordered”

Some data structures (like sets) are:
Sets → unordered → good for fast lookup
i.e Set = group of people in a room

In [ ]:
#to create list
mylist = [1, 'ali', 'three', 2, 3]
print(mylist)

[1, 'ali', 'three', 2, 3]


In [ ]:
len(mylist)

5


## Negitive Indexing 

- positive indexing start from 0
- negitive indexing start from -1

In [ ]:
print(mylist[len(mylist)-3])

three


In [ ]:
if "ali" in mylist:
    print("success")

success


In [ ]:
#to print all the elements of the list
print(mylist[:])
print(mylist[1:4])

[1, 'ali', 'three', 2, 3]
['ali', 'three', 2]


# List Methods:
1. append
2. sort()
3. remove()
4. insert(index, element)

In [ ]:
# List Methods:

# List Comprehension


In [ ]:
new_list = [i**2 for i in range(5)]
print(new_list)

[0, 1, 4, 9, 16]


# list Methods

In [ ]:
numbers = [3, 1, 4, 3, 3]

numbers.append(2)  # Adds 2 to the end
print(numbers)  # Output: [3, 1, 4, 2]

numbers.sort()  # Sorts the list
print(numbers)  # Output: [1, 2, 3, 4]

#to reverse sort the lis
numbers.sort(reverse=True)

# numbers.remove(3)  # Removes first occurrence of 3
print(numbers)  # Output: [1, 2, 4]

#count method
print(f'3 is occured {numbers.count(3)} times')

#to add element at specific index of the list
numbers.insert(0,0)
print(f"numbers list after adding element at 0 index {numbers}")


# to pop an element from array/list. 
# remember always pass index in pop() funtion 

numbers.pop(1)
print(f"after pop number at index 1 {numbers}")

# remove last number of list and array
numbers.pop()


# remove() → Remove by value

numbers.remove(3)                             # remove the first occurance of 3
print(f"after removing element 3 {numbers}")

[3, 1, 4, 3, 3, 2]
[1, 2, 3, 3, 3, 4]
[1, 2, 3, 3, 3, 4]
3 is occured 3 times
numbers list after adding element at 0 index [0, 1, 2, 3, 3, 3, 4]
after pop number at index 1 [0, 2, 3, 3, 3, 4]
after removing element 3 [0, 2, 3, 3]


# jump index
- list[start:stop:step]

In [ ]:
numbers = [3, 1, 4, 5, 6, 7]
print(numbers[0:5:2])

[3, 4, 6]


In [ ]:
marks = [32,43,44,56]

#copy() method
new_list = marks.copy()
new_list[0] = 42
print(f'copy of numbers list {new_list}')

#to extend list
m = [60,65]
new_list.extend(m)
print(f'after extending marks list {new_list}')

copy of numbers list [42, 43, 44, 56]
after extending marks list [42, 43, 44, 56, 60, 65]


# 📌 Tensors in Python (Deep Learning Context)

## 1. What is a Tensor?
- A **Tensor** is a generalization of **scalars, vectors, and matrices** to higher dimensions.
- Think of it as a **multidimensional array**.
- Widely used in **machine learning & deep learning** (PyTorch, TensorFlow).

### Tensor Examples:
- Scalar (0D tensor): `5`
- Vector (1D tensor): `[1, 2, 3]`
- Matrix (2D tensor): `[[1, 2], [3, 4]]`
- 3D Tensor: a stack of matrices (like an image with RGB channels)
- ND Tensor: any dimension (`n`-dimensional)

---

## 2. Why Do We Use Tensors?
- **Efficient computation on GPUs** (parallel processing).
- **Automatic differentiation** (for training neural networks).
- **Optimized memory layout** (similar to NumPy arrays but GPU-ready).

---

## 3. Difference Between List, NumPy Array, and Tensor

| Feature              | Python List                          | NumPy Array                           | Tensor (PyTorch / TF)          |
|----------------------|--------------------------------------|---------------------------------------|--------------------------------|
| **Data Type**        | Can store mixed types                | Must have same type (int, float, etc.) | Must have same type             |
| **Memory Storage**   | Stores references to objects         | Contiguous memory (fast)              | Contiguous + GPU support       |
| **Performance**      | Slow (overhead of objects)           | Fast (C optimized)                    | Very fast (GPU + C++ backend)  |
| **Dimensionality**   | 1D (lists of lists for higher dims)  | Multi-dimensional                     | Multi-dimensional              |
| **Math Operations**  | Manual (loops)                      | Vectorized (fast)                     | Vectorized + Autograd          |
| **GPU Support**      | ❌ No                                | ❌ No                                  | ✅ Yes                         |

---



In [ ]:
# ✅ Python List
py_list = [[1, 2], [3, 4]]
print("Python List:", py_list)

# ✅ NumPy Array
import numpy as np
np_array = np.array([[1, 2], [3, 4]])
print("NumPy Array:\n", np_array)

# ✅ PyTorch Tensor
import torch
tensor = torch.tensor([[1, 2], [3, 4]])
print("Tensor:\n", tensor)

# ✅ GPU Tensor (if available)
if torch.cuda.is_available():
    tensor_gpu = tensor.to("cuda")
    print("Tensor on GPU:", tensor_gpu)


Python List: [[1, 2], [3, 4]]
NumPy Array:
 [[1 2]
 [3 4]]
Tensor:
 tensor([[1, 2],
        [3, 4]])


# 📌 Why NumPy Arrays Don’t Work on GPUs

---

## 1. NumPy Was Designed for CPUs
- NumPy was created in **2006** for scientific computing on **CPUs**.  
- Its backend uses **C/Fortran libraries (BLAS, LAPACK)** that only run on CPUs.  
- At that time, GPU computing was not mainstream.

---

## 2. CPU vs GPU Memory
- CPUs (RAM) and GPUs (VRAM) have **separate memory spaces**.  
- To use a GPU, data must be **copied** from CPU → GPU.  
- NumPy has **no built-in system** to manage this transfer.  
- Frameworks like **PyTorch** and **TensorFlow** handle this automatically.

---

## 3. GPU Kernels (Missing in NumPy)
- A **kernel** = low-level function that runs on GPU (via CUDA).  
- NumPy operations (`np.dot`, `np.sum`, etc.) only call **CPU kernels**.  
- PyTorch/TensorFlow implement both CPU and **GPU kernels** → making tensors GPU-ready.

---

## 4. No Autograd (Gradients)
- Deep learning requires **automatic differentiation**.  
- NumPy doesn’t support autograd → no point in GPU acceleration for ML.  
- Tensors (PyTorch/TF) track operations → gradients are computed automatically.

---

# ✅ Why Tensors Work on GPUs
- Tensors are like **NumPy arrays with extra powers**:
  - GPU acceleration
  - Automatic differentiation
  - Optimized deep learning operations

Example (PyTorch):


In [ ]:
import torch

# Tensor on CPU
x = torch.ones((3, 3))

# Move tensor to GPU (if available)
if torch.cuda.is_available():
    x = x.to("cuda")
    print("Tensor on GPU:", x)
